services:
  - type: web
    name: komacut-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://comcat-backend.onrender.com/api
      - key: REACT_APP_CLIENT_URL
        value: https://komacut-frontend.onrender.com
